dist: xenial   # required for Python >= 3.7
language: python

python:
  - "3.6"
  - "3.7"

services:
  - docker

install:
  - pip install -r requirements.txt
  - docker build -t data-portal-summary-stats .

script:
  - coverage run -m unittest discover
  - docker images | grep -q data-portal*

after_success:
  - coveralls
  - codecov